### ISSUE TITLE
Get rid of redundant taxonomy_name from config

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#106]
I'm pretty sure `taxonomy_name` is redundant from the config. I think its just used in extract_skills.py at the point of 
```
if self.taxonomy_name == "toy":
            self.taxonomy_skills = load_toy_taxonomy()
        else:
```

but this could also be achieved with

```
if config_name=="extract_skills_toy":
   self.taxonomy_skills = load_toy_taxonomy()
else:
```

**Comment by india-kerle** [comment]
hmmm it's not redundant in so far as we use it for logging messages actually @lizgzil but that's its only use tbh

**Comment by lizgzil** [comment]
@india-kerle ok good to know - I guess we could use the name of the config file in the log? Just thinking of ways to slim down the configs

**Comment by india-kerle** [comment]
oh thats a great idea! lets do that

**Comment by india-kerle** [comment]
closing ticket
