### ISSUE TITLE
check over all docs

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#122]
I think some of the examples of the skills extraction are outdated.

- spell check? 
- is it "multiskill" or "multi-skill"?! 
- do all the examples of code snippets work and give the same outputs (some may be different after the hardcode step)?
- do we need to update any of the figures?

also exmaple one on main readme is wrong
```
job_skills_matched = es.extract_skills(predicted_skills) #match and extract skills to toy taxonomy
```
needs to be 
```
job_skills_matched = es.extract_skills(job_adverts) #match and extract skills to toy taxonomy
```

**Comment by india-kerle** [comment]
helpful notes on how to publish documentation with a custom GitHub Actions workflow -- https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
