### ISSUE TITLE
Time-consuming installation of the library

### ISSUE THREAD

**Issue by Delmark1904** [nestauk/ojd_daps_skills#155]
I am trying to install library ojd_daps_skills in Google Colab. It takes to long, to install all requirement (46 minutes and its not done yet). Same problem when I try to install requirement manually, pip tries to match versions so that there are no conflicts, which makes the download process very slow (Below will be pip info). I would be very grateful, if you specify versions of all libraries.

`INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking`

**Comment by lizgzil** [comment]
many thanks for this @Delmark1904 - we will try to do this soon

**Comment by lizgzil** [comment]
Address requirements properly:
move analysis/none-user requirements to requirements_dev

**Comment by lizgzil** [comment]
This should be much better now @Delmark1904
