### ISSUE TITLE
Clean up requirements

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#162]
This should also help with #160  and #155 

All with pinned versions:

- `requirements.txt` : for the use of the package only (i.e. external users)
- `requirements_dev.txt` : with extras for training the model/jupyter analysis bits + documentation/pytest ?
- `requirements_analysis_app.txt`: for the blog 2 i.e. streamlit and altair
- `requirements_app.txt`: for the demo app

Use cases:
- An external user: `requirements.txt` only
- Github integration and Nesta development: `requirements.txt` + `requirements_dev.txt`
- Running the streamlit demo app `requirements_app.txt` only
- Running the streamlit app for blog 2 `requirements_analysis_app.txt` only

**Comment by india-kerle** [comment]
good idea!
