### ISSUE TITLE
PyPI install led to "AttributeError: module 'numpy' has no attribute 'int'" when example was run

### ISSUE THREAD

**Issue by sgallen** [nestauk/ojd_daps_skills#176]
Following the instructions:

1. Ran `pipenv install ojd-daps-skills`.
2. Ran `pipenv shell`.
3. Ran `python -m spacy download en_core_web_sm`.
4. Created a file and executed the [example code](https://github.com/nestauk/ojd_daps_skills#1-extract-and-map-skills).

Received `AttributeError: module 'numpy' has no attribute 'int'` coming from:
```
...lib/python3.8/site-packages/sklearn/feature_extraction/image.py", line 172, in <module>
    dtype=np.int):
```
The issue seems to be related to the PyPI package being based on an older tag where the `numpy` version isn't pinned in the `requirements.txt` file.

Installing from a newer git tag resolves the issue as the `numpy` version is pinned to an older version where `np.int` isn't deprecated:
```
pipenv install -e git+https://github.com/nestauk/ojd_daps_skills.git@v1.1.0-beta#egg=ojd_daps_skills
```
Just sharing to save others time.

**Comment by lizgzil** [comment]
Thanks so much for this @sgallen . Great to hear the new version works - we will be releasing it properly soon

**Comment by india-kerle** [comment]
Solved in the new release !
