### ISSUE TITLE
Deal with skills not matched to ESCO

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#28]
First step:
- get a sense of the scale of this problem.

Then decide what to do about it
- Just a count of the most common skill spans which arent matched
- Expect most are junk
- but some might be new skills not in ESCO
- may also find nuances in language of the skills which could be cleaned out to better match with esco "ability to ..." 

## Before

(After deciding on the threshold/independentish)

If they don't match, can we find a way to match to an aggregated level of ESCO?

- Do we need to find the skill sentence they were in (because we might need to context)
- Could we use the commonly occurring words with the many examples of this skill entity (Excel, Excel skills, Spreadsheets in Excel)
- Matching to ESCO - some sort of tfidf/count vectoriser of aggregate descriptions from a level and match on this?

How many are we actually dealing with - can we do it manually?

**Comment by india-kerle** [comment]
Do we want to show skills that we are able to match to the highest level? or do we just want to say they were unmatched? We could even just say "unmatched" instead of calling it a skill, just in case the skill span is bad

i.e. {“SKILL”:
   [(“communicate”, (“communication”, “S1.2.2”)),
    (“excel skills”, (“microsoft excel”, “S5.1.3”)),
(“CSS”, (“unmatched”))],
“EXPERIENCE”: [“insurance sector”]} = extract_skills(text, map=True, taxonomy=’esco’)

**Comment by lizgzil** [comment]
> Do we want to show skills that we are able to match to the highest level? or do we just want to say they were unmatched? We could even just say "unmatched" instead of calling it a skill, just in case the skill span is bad

it's a good point of how best to do this, I've added to clarify things a bit more in this issue https://github.com/nestauk/ojd_daps_skills/issues/88. I think we should leave the code as it is for now, and rather tag the level 1 matches as not matched in the analysis (and make sure we make it clear we are doing this).

Then, at a later point we could change how the output is given/how best to code this in (do we do it via the config thresholds or after they are all matched to level 1s)? A pro of keeping it how it is, is that some people may want to match to level 1 as best they can (especially for other taxonomies), so maybe it's a decision we are making for our analysis to remove it rather than one that should be made across the board).

I wonder whether giving `“CSS”, None` or  `“CSS”, (None, None)`  might be more robust to bugs than setting it to a string?

**Comment by india-kerle** [comment]
@lizgzil close?
