### ISSUE TITLE
Consider evaluation

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#30]
We have data from a few different approaches to extracting (and matching) skills... EMSI, ojo1, ojo2 (soon) and ESCO (once we collaborate).

- [x] what sample of job adverts do we want?
- [x] Get skills from EMSI from these
- [ ] Get skills from ESCO from these
- [x] Get skills from OJOv2 from these
- [ ] Speak with Geuorguie about ONSs skills extraction
- [ ] Do we want a single metric approach?

**Comment by lizgzil** [comment]
Good point by Cath in our one on one about the influence of changes on the evaluation - we don't want to waste time doing manual evaluation steps if the algorithm ends up changing due to things found in the analysis! So we should:
1. Do some basic analysis - does anything look out of place? Find if changes are needed (e.g. "teach communication" needs to be hardcoded to just "communication")
2. Can write the rest of the analysis code at this point, but keep in mind that the outputs may be changing
3. If needed, make changes to locations/skills extraction algos and rerun to get finalised ojo outputs
4. Do full analysis with finalised ojo outputs
5. Do full evaluation (i.e. compare our lightcast results with the lightcast website) - however this may also surface potential bugs to fix?

**Comment by india-kerle** [comment]
from @CSleeman this morning:
- lets add the different types of errors for the SkillsExtractor - the three include: skills we couldn't extract at the NER stage, skills we don't match to and top skills we incorrectly match to
- lets also report on the effect of skill length on matches
