### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ojd_daps_skills#41]
We want documentation in our:

- [ ] directory readmes
- [ ] PyPi (which will be taken from the main readme)
- [x] MKdocs (or something similar for how to use the library)

 
We want to document:
- [x]  the end-to-end pipeline: ongoing but we want a high level diagram of how the process works
- [x] how models work: we want model cards for the models we develop

**Comment by lizgzil** [comment]
@india-kerle I think this can be closed as we have other documentation issues?

**Comment by india-kerle** [comment]
hmmm I think close this tbh as we're using #30 to document

**Comment by india-kerle** [comment]
yes!!
