### ISSUE TITLE
notes about updating classes 

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ojd_daps_skills#53]
things to change in SkillMapper:

- [x] embed taxonomy skills function - get rid filename in there: just make a save taxonomy skills function instead 
- [x] silence the CPU info

etc.
- [x] add tests for ExtractSkills
- [x] save out the ojo_esco file - even just a sample - maybe the 10 most common skill hashes we found and which esco skill they link to? Ditto most common esco embeddings to test those functions and THEN run it with the most common 
- [x] match the multiskills not just the skills!

- [x]  verbose=true -- add helpful logging comments for users
- [x]  add an example end to end 
- [x]  loading esco embeddings if we can (or lightcast?) ask @Jack-Vines to figure out where we can store all this stuff 
- [ ]  streamlit app or some kind of visual for this?

**Comment by lizgzil** [comment]
@india-kerle can we close this?

**Comment by india-kerle** [comment]
yup I think so - up for discussion on whether we want to add a streamlit app as its own issue. I reckon we could and address it only if we have time in the next sprint.
