### ISSUE TITLE
Analyse model differences

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#67]
The random shuffling in the iterations of the NER training mean that each outputted model can be quite different.

An analysis piece would be to compare a few different models and see whether any of them are better than any others.

An comparison of three model results for 20 job adverts is here https://docs.google.com/spreadsheets/d/1qfq_FtwwwdBsUlc_VbaF9t2DreqbxUkxL3WZTS2aar8/edit#gid=582620934

(but this data isn't reproducible)

**Comment by lizgzil** [comment]
@india-kerle shall we close this - can't imagine we will address it?

**Comment by india-kerle** [comment]
Ya, i reckon closing makes sense!
