### ISSUE TITLE
Sprint 5 Goals

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ojd_daps_skills#73]
Other Tasks (between sprints):
- [x] bug fixes
- [x] Re-do the aggregations
- [x] Make presentation for sprint Pre - Sprint 5 (Application) Checkpoint Meeting - 3.13 - Regional & Labour Market Statistics: Tracking Regional Skills Demands (Oct. 6th)

Analysis and Evaluation:
- [x] evaluation - how to compare the different skills extracted across different algorithms
- [x] analysis - get a start on it, Cath to present some ideas 

Notes:
- focus on specific regions?
- replicate that really nice graph Cath made about the mix of skills per region?

**Comment by lizgzil** [comment]
@india-kerle fyi closing this since I think it's all done
