### ISSUE TITLE
Experiment with hackmd and altair for analysis 

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ojd_daps_skills#78]

**Comment by india-kerle** [comment]
update - i'm finding hackmd not so easy to use whoops

**Comment by india-kerle** [comment]
for altair, we can use this codes from ai_genomics to make graphs nesta brand compliant -- https://github.com/nestauk/ai_genomics/blob/dev/ai_genomics/utils/plotting.py 

and this to save the graphs --
https://github.com/nestauk/ai_genomics/blob/dev/ai_genomics/utils/save_plotting.py

**Comment by india-kerle** [comment]
@lizgzil Should we close this? We've used altair in the last sprint and I don't think hackmd will be helpful anymore given we're trying to just give them a presentation now

**Comment by lizgzil** [comment]
@india-kerle yeh lets close it!
