### ISSUE TITLE
ERROR ANALYSIS: A basic breakdown of skills by ESCO's structure and by regions

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#81]
[brief] A basic breakdown of skills by ESCO's structure and by regions.

Remember: ESCO has some skills in multiple parts of the taxonomy, so might need to make decisions about this/double count?

- which skills need manually editing (e.g. teach communication to communication)?
- what are % of skills not matched?
- what are the unmatched ones?

**Comment by india-kerle** [comment]
notes:
- are we actually deduplicating extracted_skills?

**Comment by india-kerle** [comment]
this was explored in the last sprint, closing this issue
