### ISSUE TITLE
Exploring the variation in skill requirements within occupations (for a select group).

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#82]
e.g. for a care worker:
- what are the core skills needed? or are they all very different advert to advert (how much does it vary)?
- which are the skills sometimes and rarely mentioned?
- (extra) if the skills are very varied then are there groups of similar regions/employers

**Comment by india-kerle** [comment]
spitball with liz about how we might want to measure 'skill stability WITHIN occupations'
