### ISSUE TITLE
Intro analysis - Building a method to explore the cooccurrences of skills.

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#83]
[main part 2]

- what skills tend to cooccur with each other
- used to find complimentary skills
- the mix of transversal and technical
- mixes of transversal vs technical skills in occupations - which occupations are most mixed?

Awaiting Gueorguie's response on this

**Comment by india-kerle** [comment]
could add this as an intro in the analysis blog

**Comment by india-kerle** [comment]
- list of top transversal skills
