### ISSUE TITLE
clarify things in docs

### ISSUE THREAD

**Issue by lizgzil** [nestauk/ojd_daps_skills#88]
There are a few nuances of the package that should be clarified somewhere in the docs.

## clarify matching in docs

Make sure it's clear in the docs that the configs have been set so that every skill will be matched to a ESCO/lightcast skill. However if its matched to a level 1 skill group then we treat it as not matched. Related to #79 

## job ads which mention the same skills

Make sure to explain how if the string "excel skills" is mentioned twice in a job advert, then it is deduplicated and then one is matched to ESCO. But if it mentions the strings "excel skills" and "Excel skill" since these aren't exactly the same spans, both occurrences will be matched to ESCO and therefore the output will have two lots of Excel skills. Therefore in the output it might be best to deduplicate ESCO skills.

## Make clearer the 1 step vs 2 step process
It's either `extract_skills` OR `get_skills`+`map_skills`

## Public bucket data
More here https://github.com/nestauk/ojd_daps_skills/issues/94

**Comment by india-kerle** [comment]
I reckon we can add nuances clarify matching in docs and job ads which mention the same skills in the model cards.

**Comment by india-kerle** [comment]
add some basic analysis stats to model cards
