### ISSUE TITLE
Public access bucket, isn't so publically accessable

### ISSUE THREAD

**Issue by Aiden-RC** [nestauk/ojd_daps_skills#94]
![image](https://user-images.githubusercontent.com/108408216/199489397-59de80b2-e154-4e3c-b07e-dda1efe27b1a.png)

![image](https://user-images.githubusercontent.com/108408216/199489447-683eecac-7bb5-49f2-a67f-86bd9849dc90.png)

Hey guys, nice work :)
I'm aware this is still in development but just thought i'd point out ( as people with access wouldn't be able to notice this ), 
but the 'public access bucket' isn't actually able to be used via aws interface due to the lack of list permissions.

**Comment by lizgzil** [comment]
Hi @Aiden-RC - thanks so much for spotting this and opening an issue! We are due to focus on improving the documentation and use of this package in 2 weeks time - so will address this then and find a solution to sharing these files.

**Comment by Aiden-RC** [comment]
> Hi @Aiden-RC - thanks so much for spotting this and opening an issue! We are due to focus on improving the documentation and use of this package in 2 weeks time - so will address this then and find a solution to sharing these files.

Thank you very much,
i believe you should be able to play around with the bucket permissions to allow listing however this will list all files,
the other option is to make a readme file on here with the url to every publically available file.
Another option is zip all the resources up and make that publically accessable and list the url on the main readme of the repo :)

**Comment by lizgzil** [comment]
Hi @Aiden-RC we went with zipping up all the resources! I really hope the latest PR should mean that the data is nicely downloadable when the functions are run 

```
pip install ojd_daps_skills@git+https://github.com/nestauk/ojd_daps_skills@fix-download-public-data#egg=ojd_daps_skills
python -m spacy download en_core_web_sm
```

Then in python the following should work  (the first time `ExtractSkills()` is used the data will be downloaded to your computer)
```
from ojd_daps_skills.pipeline.extract_skills.extract_skills import ExtractSkills

es = ExtractSkills(config_name="extract_skills_toy", local=True)

es.load()

job_adverts = [
        "You will need to have good communication and excellent mathematics skills. You will have experience in the IT sector.",
        "You will need to have good excel and presenting skills. You need good excel software skills",
    ]

predicted_skills = es.get_skills(job_adverts)
job_skills_matched = es.map_skills(predicted_skills)
```

We're still in the process of neatening up all our documentation, so it may be a bit out of date at the moment. We hope to finish it all next week :)
