### ISSUE TITLE
Update readmes after library is complete

### ISSUE THREAD

**Issue by india-kerle** [nestauk/ojd_daps_skills#98]
for example, add hard_skill_name to https://github.com/nestauk/ojd_daps_skills/tree/dev/ojd_daps_skills/pipeline/extract_skills 

the skills_extraction readme: https://github.com/nestauk/ojd_daps_skills/blob/dev/outputs/reports/skills_extraction.md

**Comment by lizgzil** [comment]
@india-kerle I think this can be closed?

**Comment by india-kerle** [comment]
yup, closing
